framework:
    secret: '%env(APP_SECRET)%'
    session:
        handler_id: ~
        cookie_secure: auto
        cookie_samesite: lax
    http_client:
        default_options:
            verify_peer: true
    http_cache:
        enabled: true
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file