security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        user_provider:
            id: App\Security\User\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            provider: user_provider
            custom_authenticators:
                - App\Security\Http\RegularAuthenticator
                - App\Security\Http\OTPAuthenticator
                - App\Security\Http\IdPAuthenticator
            entry_point: App\Security\EntryPoint\AuthenticationEntryPoint
            logout:
                path: /logout
                target: /login
                invalidate_session: true
            lazy: true
            stateless: false

    access_control:
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/logout$, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: PUBLIC_ACCESS }
