security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        api_user_provider:
            id: App\Security\User\ApiUserProvider
    firewalls:
        public:
            pattern: ^/admin/tool/converter
            security: false
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            provider: api_user_provider
            custom_authenticators:
                - App\Security\Authenticator\ApiAuthenticator
            entry_point: App\Security\Authenticator\ApiAuthenticator
            logout:
                path: /logout
                target: /login
                invalidate_session: true
            stateless: false

    access_control:
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/login_check$, roles: PUBLIC_ACCESS }
        - { path: ^/logout$, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ['ROLE_ADMIN'] }
        - { path: ^/partner, roles: ['ROLE_PARTNER_ADMIN'] }
        - { path: ^/, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
