# platform.app.yaml
#Unique name for the app. Must be lowercase alphanumeric chars.
#Changing the name destroys data associated with the app
name: app
#The base image to use with a specific app language
#Format runtime:version
#For example: For c#/ .net core => dotnet:7.0
# See https://docs.platform.sh/create-apps/app-reference/single-runtime-image.html#types

#How much resources to devote to the app. Defaults to AUTO in production environments.
#See https://docs.platform.sh/create-apps/app-reference/single-runtime-image.html#sizes
# size: S (example)
#Size:

dependencies:
  php:
    composer/composer: "^2"

runtime:
  extensions:
    - apcu
    - ctype
    - iconv
    - mbstring
    - pdo_pgsql
    - sodium
    - xsl

#Connections to other services and apps.
#https://docs.platform.sh/create-apps/app-reference/single-runtime-image.html#relationships
relationships:
#  redis: "redis:redis"



build:
  flavor: composer

disk: 1024

#How the web application is served.
#https://docs.platform.sh/create-apps/app-reference/single-runtime-image.html#web

web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"

#Directories that are writable even after the app is built. If set as a local source disk is required
# https://docs.platform.sh/create-apps/app-reference/single-runtime-image.html#mounts

mounts:

hooks:
  build: |

  deploy: |


crons:
  security-check:
    # Check that no security issues have been found for PHP packages deployed in production
    # See https://github.com/fabpot/local-php-security-checker
    spec: '50 23 * * *'
    cmd: if [ "$PLATFORM_ENVIRONMENT_TYPE" = "production" ]; then croncape php-security-checker; fi
