controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_login_regular:
    path: /login_check/regular
    methods: [POST]
app_login_idp:
    path: /login_check/idp
app_login_otp:
    path: /login_check/otp
    methods: [POST]

app_logout:
    path: /logout