parameters:
    elastic_url: '%env(ELASTIC_URL)%'
    api_url: '%env(API_URL)%'
services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Provider\ElasticaManagerProvider:
        arguments:
            $managers: !tagged_iterator 'app.elastica'

    App\Security\Voter\:
        resource: '../src/Security/Voter'
        tags: ['security.voter']

    App\EventSubscriber\ExceptionSubscriber:
        arguments:
            $router: '@router'
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    App\Manager\Elastica\ElasticaAutocompleteManager:
        tags:
            - { name: app.elastica }
    App\Manager\Elastica\ElasticaTextManager:
        tags:
            - { name: app.elastica }
    App\Manager\Elastica\ElasticaDocManager:
        tags:
            - { name: app.elastica }
    App\Manager\Elastica\ElasticaSearchManager:
        tags:
            - { name: app.elastica }